const repos = [
  { name: 'mission-control-be' },
  { name: 'mission-control-fe' },
  { name: 'CS10-restaurant-pos', isFork: false },
  { name: 'anchored.app', isFork: false },
  { name: 'prismatopia', isFork: false },
  { name: 'Attendance', isFork: false },
  { name: 'designhub-fe', isFork: false },
  { name: 'labspt2-investor-data-app', isFork: false },
  { name: 'labspt2-scratch-and-map', isFork: false },
  { name: 'labspt2-auto-invoicer', isFork: false },
  { name: 'paperStack', isFork: false },
  { name: 'sauti-africa-market-price-data-fe', isFork: false },
  { name: 'Labs8-AdventureTracker', isFork: false },
  { name: 'Airtable-ORM', isFork: false },
  { name: 'forest-fire-watch-ds', isFork: false },
  { name: 'sauti-africa-market-price-data-be', isFork: false },
  { name: 'Labs8-AutoInvoicer', isFork: false },
  { name: 'student-art-collection-fe', isFork: false },
  { name: 'CS10-ksl-alerts', isFork: false },
  { name: 'student-art-collection-be', isFork: false },
  { name: 'tally-ai-ds', isFork: false },
  { name: 'trashpanda-ds-api', isFork: false },
  { name: 'buddy-app-fe', isFork: false },
  { name: 'well-done-android2', isFork: false },
  { name: 'refresh-be', isFork: false },
  { name: 'sauti-databank-be', isFork: false },
  { name: 'AdaptivApps-fe', isFork: false },
  { name: 'AdaptivApps-be', isFork: false },
  { name: 'net-giver-asset-manager-be', isFork: false },
  { name: 'Admin-Tools-API', isFork: false },
  { name: 'student-art-collection-android', isFork: false },
  { name: 'buddy-app-android', isFork: false },
  { name: 'airbnb-unit-price-analysis-be', isFork: false },
  { name: 'airbnb-unit-price-analysis-ds', isFork: false },
  { name: 'airbnb-unit-price-analysis-fe', isFork: false },
  { name: 'FE-Project-Notes', isFork: false },
  { name: 'allay-be', isFork: false },
  { name: 'allegiance-fe', isFork: false },
  { name: 'allegiance-ios', isFork: false },
  { name: 'flashcards-android', isFork: false },
  { name: 'allay-fe', isFork: false },
  { name: 'allegiance-be', isFork: false },
  { name: 'hackathon-portal-android', isFork: false },
  { name: 'github-commit-analysis-ds', isFork: false },
  { name: 'Job-Funnel-ds-API', isFork: false },
  { name: 'tally-ai-be', isFork: false },
  { name: 'github-commit-analysis-fe', isFork: false },
  { name: 'community-calendar-android', isFork: false },
  { name: 'buddy-app-be', isFork: false },
  { name: 'tally-ai-fe', isFork: false },
  { name: 'labspt2-ksl-alerts', isFork: false },
  { name: 'forest-fire-watch-android', isFork: false },
  { name: 'github-commit-analysis-be', isFork: false },
  { name: 'Admin-Tools-Client', isFork: false },
  { name: 'buddy-app-ios', isFork: false },
  { name: 'adaptivapps-2-be', isFork: false },
  { name: 'student-art-collection-iOS', isFork: false },
  { name: 'net-giver-asset-manager-fe', isFork: false },
  { name: 'well-done-fe', isFork: false },
  { name: 'community-calendar-fe', isFork: false },
  { name: 'community-calendar-be', isFork: false },
];

export default repos;
